[2023-05-14T15:48:00.063+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alert_dag.t1 scheduled__2019-01-31T00:00:00+00:00 [queued]>
[2023-05-14T15:48:00.589+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alert_dag.t1 scheduled__2019-01-31T00:00:00+00:00 [queued]>
[2023-05-14T15:48:00.593+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-14T15:48:00.634+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): t1> on 2019-01-31 00:00:00+00:00
[2023-05-14T15:48:00.665+0000] {standard_task_runner.py:57} INFO - Started process 215 to run task
[2023-05-14T15:48:00.691+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'alert_dag', 't1', 'scheduled__2019-01-31T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/alert_dag.py', '--cfg-path', '/tmp/tmpe9d585kf']
[2023-05-14T15:48:00.703+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask t1
[2023-05-14T15:48:00.875+0000] {task_command.py:410} INFO - Running <TaskInstance: alert_dag.t1 scheduled__2019-01-31T00:00:00+00:00 [running]> on host ccd7d24ea349
[2023-05-14T15:48:01.091+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='alert_dag' AIRFLOW_CTX_TASK_ID='t1' AIRFLOW_CTX_EXECUTION_DATE='2019-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-31T00:00:00+00:00'
[2023-05-14T15:48:01.098+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-14T15:48:01.103+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-05-14T15:48:01.131+0000] {subprocess.py:86} INFO - Output:
[2023-05-14T15:48:01.138+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-14T15:48:01.221+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-14T15:48:01.234+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=alert_dag, task_id=t1, execution_date=20190131T000000, start_date=20230514T154800, end_date=20230514T154801
[2023-05-14T15:48:01.282+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 36 for task t1 (Bash command failed. The command returned a non-zero exit code 1.; 215)
[2023-05-14T15:48:01.321+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-14T15:48:01.396+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
