[2023-05-14T15:50:23.244+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alert_dag.t1 scheduled__2019-07-01T00:00:00+00:00 [queued]>
[2023-05-14T15:50:23.836+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alert_dag.t1 scheduled__2019-07-01T00:00:00+00:00 [queued]>
[2023-05-14T15:50:23.837+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-14T15:50:24.179+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): t1> on 2019-07-01 00:00:00+00:00
[2023-05-14T15:50:24.247+0000] {standard_task_runner.py:57} INFO - Started process 863 to run task
[2023-05-14T15:50:24.271+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'alert_dag', 't1', 'scheduled__2019-07-01T00:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/alert_dag.py', '--cfg-path', '/tmp/tmpx1syeont']
[2023-05-14T15:50:24.288+0000] {standard_task_runner.py:85} INFO - Job 189: Subtask t1
[2023-05-14T15:50:24.582+0000] {task_command.py:410} INFO - Running <TaskInstance: alert_dag.t1 scheduled__2019-07-01T00:00:00+00:00 [running]> on host ccd7d24ea349
[2023-05-14T15:50:25.008+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='alert_dag' AIRFLOW_CTX_TASK_ID='t1' AIRFLOW_CTX_EXECUTION_DATE='2019-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-07-01T00:00:00+00:00'
[2023-05-14T15:50:25.023+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-14T15:50:25.036+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-05-14T15:50:25.152+0000] {subprocess.py:86} INFO - Output:
[2023-05-14T15:50:25.170+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-14T15:50:25.204+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-14T15:50:25.222+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=alert_dag, task_id=t1, execution_date=20190701T000000, start_date=20230514T155023, end_date=20230514T155025
[2023-05-14T15:50:25.583+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 189 for task t1 (Bash command failed. The command returned a non-zero exit code 1.; 863)
[2023-05-14T15:50:25.683+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-14T15:50:25.812+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
